channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    # Initial version is required to configure Atari ROMS in setup_env.sh
    - gym==0.13
    - gym[accept-rom-license]
    - gym[atari]
    - hypothesis
    - future
    - cloudpickle
    - pygame
    - moviepy
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - dm_control -e git+https://github.com/deepmind/dm_control.git@c053360edea6170acfd9c8f65446703307d9d352#egg={dm_control}
    - patchelf
    - pyopengl==3.1.4
